export enum CharacterClass {
  ARTEFICER = "arteficer",
  BABARIAN = "barbarian",
  BARD = "bard",
  CLERIC = "cleric",
  DRUID = "druid",
  FIGHTER = "fighter",
  MONK = "monk",
  PALADIN = "paladin",
  RANGER = "ranger",
  ROUGE = "rouge",
  SORCERER = "sorcerer",
  WARLOCK = "warlock",
  WIZARD = "wizard",
}
