import { Alignment } from "../model/alignment";
import { CharacterClass } from "../model/character-class";
import type { CharacterSheet } from "../model/character-sheet";
import { AllSkills, ATTRIBUTE_SKILLS, Attribute } from "../model/skill";
import { Species } from "../model/species";
import { Spell } from "../model/spell";
import { Weapon } from "../model/weapon";

export class CharacterService {
  public static findAttributeBySkill(skill: AllSkills): Attribute {
    for (const attr in ATTRIBUTE_SKILLS) {
      if (ATTRIBUTE_SKILLS[attr as Attribute].includes(skill as never)) {
        return attr as Attribute;
      }
    }
    throw new Error("Skill not found");
  }

  public static getEmptyCharacter(): CharacterSheet {
    return {
      name: "",
      background: "",
      class: CharacterClass.FIGHTER,
      species: Species.Human,
      subclass: null,
      level: 0,
      xp: 0,
      armorClass: 0,
      currentHitpoints: 0,
      temporaryHitpoints: 0,
      spentHitDice: 0,
      maxHitpoints: 0,
      hitDiceValue: 0,
      successDeathSaves: 0,
      failedDeathSaves: 0,
      proficiencyBonus: 0,
      skills: {
        strength: {
          athletics: {
            expertise: false,
            modifier: 0,
            proficiency: true,
          },
        },
        charisma: {
          deception: { expertise: false, modifier: 0, proficiency: true },
          intimidation: { expertise: false, modifier: 0, proficiency: true },
          performance: { expertise: false, modifier: 0, proficiency: true },
          persuasion: { expertise: false, modifier: 0, proficiency: true },
        },
        constitution: {},
        dexterity: {
          acrobatics: { expertise: false, modifier: 0, proficiency: true },
          sleightOfHand: { expertise: false, modifier: 0, proficiency: true },
          stealth: { expertise: false, modifier: 0, proficiency: true },
        },
        intelligence: {
          arcana: { expertise: false, modifier: 0, proficiency: true },
          history: { expertise: false, modifier: 0, proficiency: true },
          investigation: { expertise: false, modifier: 0, proficiency: true },
          nature: { expertise: false, modifier: 0, proficiency: true },
          religion: { expertise: false, modifier: 0, proficiency: true },
        },
        wisdom: {
          animalHandling: { expertise: false, modifier: 0, proficiency: true },
          insight: { expertise: false, modifier: 0, proficiency: true },
          medicine: { expertise: false, modifier: 0, proficiency: true },
          perception: { expertise: false, modifier: 0, proficiency: true },
          survival: { expertise: false, modifier: 0, proficiency: true },
        },
      },
      attributes: {
        charisma: {
          expertise: false,
          modifier: 0,
          proficiency: false,
          savingThrow: 0,
          value: 10,
        },
        constitution: {
          expertise: false,
          modifier: 0,
          proficiency: false,
          savingThrow: 0,
          value: 10,
        },
        dexterity: {
          expertise: false,
          modifier: 0,
          proficiency: false,
          savingThrow: 0,
          value: 10,
        },
        intelligence: {
          expertise: false,
          modifier: 0,
          proficiency: false,
          savingThrow: 0,
          value: 10,
        },
        strength: {
          expertise: false,
          modifier: 0,
          proficiency: false,
          savingThrow: 0,
          value: 10,
        },
        wisdom: {
          expertise: false,
          modifier: 0,
          proficiency: false,
          savingThrow: 0,
          value: 10,
        },
      },
      heroicInspiration: false,
      lightArmorTraining: false,
      mediumArmorTraining: false,
      heavyArmorTraining: false,
      shieldTraining: false,
      weaponTrainingSimple: false,
      weaponTrainingMartial: false,
      toolProficiencies: [],
      initiative: 0,
      speed: 9,
      size: "Medium",
      passivePerception: 0,
      weapons: [],
      damageCantrips: [],
      classFeatures: [],
      speciesTraits: [],
      feats: [],
      spellcastingAbility: null,
      spellSaveDC: 0,
      spellAttackBonus: 0,
      totalSpellSlots1: 0,
      totalSpellSlots2: 0,
      totalSpellSlots3: 0,
      totalSpellSlots4: 0,
      totalSpellSlots5: 0,
      totalSpellSlots6: 0,
      totalSpellSlots7: 0,
      totalSpellSlots8: 0,
      totalSpellSlots9: 0,
      usedSpellSlots1: 0,
      usedSpellSlots2: 0,
      usedSpellSlots3: 0,
      usedSpellSlots4: 0,
      usedSpellSlots5: 0,
      usedSpellSlots6: 0,
      usedSpellSlots7: 0,
      usedSpellSlots8: 0,
      usedSpellSlots9: 0,
      cantripsAndPreparedSpells: [],
      appearance: "",
      backstory: "",
      alignment: Alignment.TRUE_NEUTRAL,
      languages: ["Common"],
      equipment: [],
      attunedMagicItems: [],
      copper: 0,
      silver: 0,
      electrum: 0,
      gold: 0,
      platinum: 0,
    };
  }

  public static getTestCharacter(): CharacterSheet {
    return {
      name: "Test Character",
      background: "A brave adventurer",
      class: CharacterClass.FIGHTER,
      species: Species.Human,
      subclass: "Champion",
      level: 5,
      xp: 6500,
      armorClass: 16,
      currentHitpoints: 38,
      temporaryHitpoints: 0,
      spentHitDice: 0,
      maxHitpoints: 38,
      hitDiceValue: 10,
      successDeathSaves: 0,
      failedDeathSaves: 0,
      proficiencyBonus: 3,
      skills: {
        strength: {
          athletics: {
            expertise: false,
            modifier: 1,
            proficiency: true,
          },
        },
        charisma: {
          deception: { expertise: false, modifier: 1, proficiency: true },
          intimidation: { expertise: false, modifier: 1, proficiency: true },
          performance: { expertise: false, modifier: 1, proficiency: true },
          persuasion: { expertise: false, modifier: 1, proficiency: true },
        },
        constitution: {},
        dexterity: {
          acrobatics: { expertise: false, modifier: 1, proficiency: true },
          sleightOfHand: { expertise: false, modifier: 1, proficiency: true },
          stealth: { expertise: false, modifier: 1, proficiency: true },
        },
        intelligence: {
          arcana: { expertise: false, modifier: 1, proficiency: true },
          history: { expertise: false, modifier: 1, proficiency: true },
          investigation: { expertise: false, modifier: 1, proficiency: true },
          nature: { expertise: false, modifier: 1, proficiency: true },
          religion: { expertise: false, modifier: 1, proficiency: true },
        },
        wisdom: {
          animalHandling: { expertise: false, modifier: 1, proficiency: true },
          insight: { expertise: false, modifier: 1, proficiency: true },
          medicine: { expertise: false, modifier: 1, proficiency: true },
          perception: { expertise: false, modifier: 1, proficiency: true },
          survival: { expertise: false, modifier: 1, proficiency: true },
        },
      },
      attributes: {
        charisma: {
          expertise: false,
          modifier: 1,
          proficiency: false,
          savingThrow: 4,
          value: 11,
        },
        constitution: {
          expertise: false,
          modifier: 1,
          proficiency: false,
          savingThrow: 4,
          value: 11,
        },
        dexterity: {
          expertise: false,
          modifier: 1,
          proficiency: false,
          savingThrow: 4,
          value: 11,
        },
        intelligence: {
          expertise: false,
          modifier: 1,
          proficiency: false,
          savingThrow: 4,
          value: 11,
        },
        strength: {
          expertise: false,
          modifier: 1,
          proficiency: false,
          savingThrow: 4,
          value: 11,
        },
        wisdom: {
          expertise: false,
          modifier: 1,
          proficiency: false,
          savingThrow: 4,
          value: 11,
        },
      },
      heroicInspiration: false,
      lightArmorTraining: true,
      mediumArmorTraining: true,
      heavyArmorTraining: false,
      shieldTraining: true,
      weaponTrainingSimple: true,
      weaponTrainingMartial: true,
      toolProficiencies: ["Smith's Tools"],
      initiative: 1,
      speed: 30,
      size: "Medium",
      passivePerception: 9,
      weapons: [
        new Weapon({
          name: "Longsword",
          attackBonus: 5,
          difficultyBonus: 3,
          damage: "1d8+3",
          damageType: "Slashing",
          notes: "Versatile (1d10)",
        }),
        new Weapon({
          name: "Shortbow",
          attackBonus: 5,
          difficultyBonus: 3,
          damage: "1d6+3",
          damageType: "Piercing",
          notes: "Range 80/320",
        }),
      ],
      damageCantrips: [],
      classFeatures: ["Second Wind", "Action Surge"],
      speciesTraits: ["Human Resilience"],
      feats: ["Great Weapon Fighting"],
      spellcastingAbility: null,
      spellSaveDC: 1,
      spellAttackBonus: 3,
      totalSpellSlots1: 4,
      totalSpellSlots2: 3,
      totalSpellSlots3: 3,
      totalSpellSlots4: 3,
      totalSpellSlots5: 3,
      totalSpellSlots6: 2,
      totalSpellSlots7: 1,
      totalSpellSlots8: 0,
      totalSpellSlots9: 0,
      usedSpellSlots1: 1,
      usedSpellSlots2: 0,
      usedSpellSlots3: 2,
      usedSpellSlots4: 0,
      usedSpellSlots5: 0,
      usedSpellSlots6: 0,
      usedSpellSlots7: 0,
      usedSpellSlots8: 0,
      usedSpellSlots9: 0,
      cantripsAndPreparedSpells: [Spell.getTestSpell()],
      appearance:
        "A tall, muscular human with short brown hair and green eyes.",
      backstory:
        "Born in a small village, this character grew up learning the ways of the sword. After their village was attacked by bandits, they set out on a quest for justice and adventure.",
      alignment: Alignment.LAWFUL_GOOD,
      languages: ["Common", "Dwarvish"],
      equipment: [
        "Explorer's Pack",
        "Tinderbox",
        "Rations (1 day)",
        "Waterskin",
      ],
      attunedMagicItems: [
        "Amulet of Health",
        "Cloak of Protection",
        "Ring of Protection",
      ],
      copper: 10,
      silver: 5,
      electrum: 0,
      gold: 20,
      platinum: 0,
    };
  }
}
